# Generated by Django 3.1.4 on 2021-05-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticastipo1',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
