# Generated by Django 3.1.4 on 2021-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, choices=[('0', 'Sin Alerta'), ('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4'), ('5', 'Nivel 4 I'), ('6', 'Nivel 4 II')], max_length=5, null=True)),
                ('cierre_perimetral', models.BooleanField(blank=True, null=True)),
                ('horarios_ocio_nocturno', models.CharField(blank=True, max_length=5, null=True)),
                ('aforo_ocio_nocturno_exterior', models.CharField(blank=True, max_length=5, null=True)),
                ('aforo_ocio_nocturno_interior', models.CharField(blank=True, max_length=5, null=True)),
                ('horario_hosteleria', models.CharField(blank=True, max_length=5, null=True)),
                ('aforo_hosteleria_nocturno_exterior', models.CharField(blank=True, max_length=5, null=True)),
                ('aforo_hosteleria_nocturno_interior', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
