# Generated by Django 3.1.4 on 2021-05-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntervaloEdad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField(blank=True, null=True)),
                ('fin', models.IntegerField(blank=True, null=True)),
                ('tipo_de_vacuna', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apodo', models.CharField(blank=True, max_length=20, null=True)),
                ('dias_hasta_efectividad', models.IntegerField(blank=True, null=True)),
                ('numero_de_dosis', models.IntegerField(blank=True, null=True)),
                ('intervalo_dosis', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
